# Generated by Django 3.2.8 on 2021-10-28 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='negative unit number'), django.core.validators.MaxValueValidator(48, message='to much unit number')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nodes.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mng_ip', models.CharField(max_length=15)),
                ('sn', models.CharField(max_length=30)),
                ('unit_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='negative unit number'), django.core.validators.MaxValueValidator(48, message='to much unit number')])),
                ('hostname', models.CharField(max_length=30)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.comments')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nodes.models')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.customers')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.racks')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.customers'),
        ),
    ]
