# Generated by Django 3.2.8 on 2021-10-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_racks_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.comments'),
        ),
    ]
