# Generated by Django 3.2.8 on 2021-10-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_alter_units_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.customers'),
        ),
    ]
