# Generated by Django 3.2.8 on 2021-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_alter_units_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
