# Generated by Django 3.2.8 on 2021-10-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_alter_customers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
