# Generated by Django 3.2.8 on 2021-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0012_alter_customers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
