# Generated by Django 3.2.8 on 2021-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0014_auto_20211029_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='hostname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
