# Generated by Django 3.2.8 on 2021-10-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0016_auto_20211029_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='comment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.comments'),
        ),
    ]
