# Generated by Django 3.2.8 on 2021-10-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0017_alter_units_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.comments'),
        ),
        migrations.AlterField(
            model_name='units',
            name='mng_ip',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
