# Generated by Django 3.2.8 on 2021-10-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0022_alter_units_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='owner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.customers'),
        ),
    ]
