# Generated by Django 3.2.8 on 2021-11-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0023_alter_units_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='comment',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.comments'),
        ),
    ]
