# Generated by Django 3.2.8 on 2021-11-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0026_auto_20211106_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='unit',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.units'),
        ),
    ]
