# Generated by Django 3.2.8 on 2021-11-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0029_auto_20211107_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nodes.models'),
        ),
    ]
