# Generated by Django 3.2.8 on 2021-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0030_alter_units_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='sn',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
