# Generated by Django 3.2.8 on 2021-11-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0032_alter_units_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='unit',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nodes.units'),
        ),
    ]
