# Generated by Django 3.2.8 on 2021-11-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0033_auto_20211107_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.customers'),
        ),
    ]
