# Generated by Django 3.2.8 on 2021-11-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0034_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
