# Generated by Django 3.2.8 on 2021-11-07 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0036_auto_20211107_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='units_takes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='negative unit number'), django.core.validators.MaxValueValidator(5, message='to much unit number')]),
        ),
    ]
