# Generated by Django 3.2.8 on 2021-11-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0037_models_units_takes'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='in_used',
            field=models.BooleanField(default=False),
        ),
    ]
