# Generated by Django 3.2.8 on 2021-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0040_rename_in_used_units_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='hostname',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
