# Generated by Django 3.2.8 on 2021-11-09 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0041_alter_units_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='created',
            field=models.DateTimeField(default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='units',
            name='modified',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
