# Generated by Django 3.2.8 on 2021-11-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0042_auto_20211109_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='created',
        ),
        migrations.RemoveField(
            model_name='units',
            name='modified',
        ),
    ]
