# Generated by Django 3.2.8 on 2021-11-09 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0043_auto_20211109_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 21, 32, 31, 531651), editable=False),
        ),
        migrations.AddField(
            model_name='units',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 21, 32, 31, 531665)),
        ),
    ]
