# Generated by Django 3.2.8 on 2021-11-09 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0044_auto_20211109_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 18, 39, 45, 865278, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='units',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 18, 39, 45, 865291, tzinfo=utc)),
        ),
    ]
